
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: webdriverio-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18.13.0
        - name: Install
          run: npm install
        - name: Debug
          run: |
            echo "Environment Variables:"
            env

            echo "Chrome Version:"
            google-chrome --version

            echo "ChromeDriver Version:"
            chromedriver --version

            ls -l /opt/google/chrome/chrome
            ls -l /path/to/chromedriver
        - name: Test
          run: BROWSERSTACK_USERNAME=${{secrets.BROWSERSTACK_USERNAME}} BROWSERSTACK_ACCESS_KEY=${{secrets.BROWSERSTACK_ACCESS_KEY}} npm run run-regression-test-cases-chrome
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
