name: Regression Tests

on:
  push:
  pull_request:

jobs:
  regression-tests:
    timeout-minutes: 10
    name: Run Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Dependecies
        run: npm install

      - name: Run Regression Tests Chrome
        run: BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }} BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }} npm run run-regression-test-cases-chrome

      - name: Allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 5

      - name: Allure Publish
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history