# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: webdriverio-ci

on:
  push:
  pull_request:

jobs:
  regression-test:
    timeout-minutes: 5
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18.13.0
        - name: Install Dependecies
          run: npm install
        - name: Run Regression Tests Chrome 
          run: BROWSERSTACK_USERNAME=${{secrets.BROWSERSTACK_USERNAME}} BROWSERSTACK_ACCESS_KEY=${{secrets.BROWSERSTACK_ACCESS_KEY}} npm run run-regression-test-cases-chrome
        - name: Generate Allure Report
          run: |
            npm install -g allure-commandline 
            allure generate --clean app/build/reports/allure -o allure-report
            mv allure-report $GITHUB_WORKSPACE
          continue-on-error: true 
        - name: Upload Allure Report
          uses: actions/upload-artifact@v2
          with:
            name: allure-report
            path: $GITHUB_WORKSPACE/allure-report
